#!/bin/sh
MODULEPATH=`mktemp -d`
LIST=`mktemp`
for module in $*
do
  echo "Download $module and its dependencies..."
  puppet module install $module --modulepath=$MODULEPATH > /dev/null
done

echo "Module download complete. Generating Puppetfile."

puppet module list --modulepath=$MODULEPATH > $LIST

sed -i.bak "s/^\/.*/forge 'http:\/\/forge.puppetlabs.com'\n/" $LIST
sed -i.bak "s/-/\//" $LIST
sed -i.bak "s/├── /mod '/" $LIST
sed -i.bak "s/└── /mod '/" $LIST
sed -i.bak "s/ (/', '/" $LIST
sed -i.bak "s/v\([[:digit:]]\)/1/" $LIST
sed -i.bak "s/)/'/" $LIST

echo
echo "Here is your suggested Puppetfile:"
echo "----------------------------------"
echo ""
cat $LIST

rm $LIST $LIST.bak
rm -fR $MODULEPATH
