#!/bin/sh

MODULEPATH="$(mktemp -d)"
LIST="$(mktemp)"
for module in "$@"; do
  echo "Download $module and its dependencies..."
  puppet module install "$module" --modulepath="$MODULEPATH" > /dev/null
done

echo 'Module download complete. Generating Puppetfile.'

puppet module list --modulepath="$MODULEPATH" | \
  sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" > "$LIST"

sed -i.bak "
	s/^\/.*/forge 'http:\/\/forge.puppetlabs.com'\n/
	s/-/\//
	s/├── /mod '/
	s/└── /mod '/
	s/ (/', '/
	s/v\([[:digit:]]\)/\1/
	s/)/'/
" "$LIST"

echo
echo 'Here is your suggested Puppetfile:'
echo '----------------------------------'
echo
cat "$LIST"

rm "$LIST" "$LIST".bak
rm -fR "$MODULEPATH"
