rm -fR /tmp/tmp.ElljPpi0qe/*
puppet module install abrader/gms --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install alexharvey/disable_transparent_hugepage --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install alexharvey/firewall_multi --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install arioch/redis --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install camptocamp/augeas --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install camptocamp/dell --modulepath /tmp/tmp.ElljPpi0qe -d  -d 
puppet module install camptocamp/kmod --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install camptocamp/openldap --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install camptocamp/systemd --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install ceh/freetds --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install dalen/dnsquery --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install dalen/puppetdbquery --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install darin/zypprepo --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install davidb/dhcpd --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install derdanne/nfs --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install garethr/docker --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install herculesteam/augeasproviders_core --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install herculesteam/augeasproviders_shellvar --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install herculesteam/augeasproviders_sysctl --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install inkblot/ipcalc --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/django --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/ekahau_throughput_server --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/freeradius --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/galera_innoptimizer --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/hddtemp --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/iperf --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/lm_sensors --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/mod_auth_cas --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/motd --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/nagios --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/networker --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/oracleinstantclient --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/percona_toolkit --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/rpmgpgkey --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/sqlmap --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/winbind --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jgazeley/yumupdate --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install jonnyx/logwatch --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install juniorsysadmin/irqbalance --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install leinaddm/htpasswd --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install lwf/remote_file --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install maestrodev/wget --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install pcfens/ca_cert --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install pfmooney/mit_krb5 --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppet/archive --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppet/logrotate --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppet/selinux --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppet/staging --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/apache --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/apt --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/apt --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/concat --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/firewall --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/gcc --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/git --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/inifile --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/java --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/mysql --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/ntp --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/pe_gem --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/postgresql --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/puppet_agent --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/ruby --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/stdlib --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/tftp --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/translate --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/vcsrepo --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install puppetlabs/xinetd --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install razorsedge/network --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install razorsedge/vmwaretools --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/dnsmasq --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/resolv_conf --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/rsyslog --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/ssh --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/sudo --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install saz/timezone --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install stahnma/epel --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install stankevich/python --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install stm/debconf --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install stm/haveged --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install thias/postfix --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install thias/sysctl --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install thrnio/ip --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install treydock/gpg_key --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install treydock/repo_centos --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install unibet/forge_server --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install wolfspyre/vmware_puppetfact --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install yelp/netstdlib --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install zleslie/permute --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module install zleslie/pxe --modulepath /tmp/tmp.ElljPpi0qe -d 
puppet module list --modulepath /tmp/tmp.ElljPpi0qe
