#!/bin/sh

MODULEPATH="$(mktemp -d)"
LIST="$(mktemp)"

function usage {
  echo "USAGE:"
  echo "$0 <module> [<module> ... <module>]"
  echo ""
}

if [ -z "$@" ]
then
  usage
  exit
fi

for module in "$@"; do
  echo "Download $module and its dependencies..."
  puppet module install "$module" --modulepath="$MODULEPATH" > /dev/null
  if [ "$?" != 0 ]
  then
    echo "Failed to download module $module properly. Check the name and internet connectivity and try again."
    exit
  fi
done

echo 'Module download complete. Generating Puppetfile.'

puppet module list --modulepath="$MODULEPATH" | \
  sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" > "$LIST"

sed -i.bak "
	s/^\/.*/forge 'http:\/\/forge.puppetlabs.com'\n/
	s/-/\//
	s/├── /mod '/
	s/└── /mod '/
	s/ (/', '/
	s/v\([[:digit:]]\)/\1/
	s/)/'/
" "$LIST"

echo
echo 'Here is your suggested Puppetfile:'
echo '----------------------------------'
echo
cat "$LIST"

rm "$LIST" "$LIST".bak
rm -fR "$MODULEPATH"
